---
title: "Lab 4, week 6"
author: "Pulindu Ratnasekera"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We are going to make one more round of modifications to 
our `recpart_fwd()` before generalizing to the MARS `fwd_stepwise()`
function. 

1. Let $H(\eta)$ be the step function defined on page 11 of the 
Friedman paper. Write an R function to implement this. 
In `recpart_fwd()`, when you split parent basis 
function $B_m$ into two children use your $H()$ instead of 
`(x[,v]>t)` and `(x[,v]<=t)`; i.e., make the 
children with ` B[,m]*H(+(x[,v]-t))` and ` B[,m]*H(-(x[,v]-t))`.
    * Note: I'm getting multiple splits on the same variable/split point
    when I use this alternative specification of the mirror-image step 
    functions. For example, my function splits three times on variable 1
    at split point 0.4609.
    I think it is because both $H(\eta)$ and $H(-\eta)$ are 
    equal to 1 at $\eta=0$ and so aren't really mirror-image. 
    While this implementation has problems, I think it will lead to 
    an easier transition to MARS next week.

2. When the best split (combination of m, v and t) is chosen
by the three inner for loops of your function, record them
in a modified version of `splits` that is a list,  whose elements
record the  $(s,v,t)$ triplets that make up each basis function. 
Suppose that
$B_m(x) = \prod_{k=1}^{K_m} H[s_{km}(x_{v(k,m)} - t_{km})]$, where
$s_{km} = \pm1$, $v_{k,m}$ is the index of the splitting variable
and $t_{km}$ is the split point. Then `splits[[m]]` is the 
data frame with elements
$$
\left[ \begin{array}{ccc} 
s_{1m} & v(1,m) & t_{1m} \\
s_{2m} & v(2,m) & t_{2m} \\
\cdots & \cdots & \cdots \\
s_{K_mm} & v(K_m,m) & t_{K_mm} \\
\end{array} \right]
$$

    a) Initialize `splits` to be an empty list of length $M_{max}$.
    b) When a basis function `B[,m]` is chosen to split into children
    `B[,m]*H(+(x[,v]-t))` and `B[,m]*H(-(x[,v]-t))`, make the 
    following modifications to `splits`: (i) copy the data frame
    `splits[[m]]` into `splits[[M+1]]` and add a row 
    (s,v,t) to `splits[[M+1]]` with `s=-1` and v and t from the best split, and (ii) 
    add a row (s,v,t) to `splits[[m]]`  where `s=+1` and v and t are from 
    the best split. In doing so you are recording how each basis
    function $B_m$ is a product of step functions.
    
3. Put your code, including the following test, in a source file called
`recpart_fwd.R` and commit the file to your group's project folder
on the SFUStat360Project repository.

```
# Test
set.seed(123); n <- 10
x <- data.frame(x1=rnorm(n),x2=rnorm(n))
y <- rnorm(n)
rp_fwd <- recpart_fwd(y,x,Mmax=9)
rp_fwd$splits
```